version: "3"
services:
  mysql:
    image: mysql
    ports:
      - 33061:3306
    environment:
      - MYSQL_DATABASE=ecomm
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
      - MYSQL_ROOT_PASSWORD=pwd
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
